import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 52,
      paddingBottom: 13,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      backgroundColor: colors.background,
    },
    headerTitle: { color: colors.textStrong, fontSize: 18, fontWeight: '800' },
    headerSpacer: { width: 40, height: 40 },
    choiceContent: { padding: 20 },
    choiceTitle: {
      color: colors.textStrong,
      fontSize: 24,
      fontWeight: '800',
      marginBottom: 20,
    },
    choiceCard: {
      minHeight: 92,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      marginBottom: 13,
      paddingHorizontal: 16,
      paddingVertical: 15,
      borderRadius: 19,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    choiceIcon: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 15,
      backgroundColor: colors.primarySoft,
    },
    choiceCopy: { flex: 1 },
    choiceCardTitle: { color: colors.textStrong, fontSize: 16, fontWeight: '800' },
    choiceDescription: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 4,
    },
    peopleContent: { flex: 1 },
    groupNameSection: { paddingHorizontal: 20, paddingTop: 18 },
    fieldLabel: { color: colors.textStrong, fontSize: 13, fontWeight: '700', marginBottom: 7 },
    groupNameInput: {
      height: 46,
      paddingHorizontal: 14,
      borderRadius: 14,
      color: colors.textStrong,
      fontSize: 15,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchBar: {
      height: 46,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      marginHorizontal: 20,
      marginTop: 16,
      paddingHorizontal: 14,
      borderRadius: 15,
      backgroundColor: colors.inputSurface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: { flex: 1, color: colors.textStrong, fontSize: 15 },
    userList: { paddingHorizontal: 20, paddingTop: 15, paddingBottom: 24 },
    emptyList: { flexGrow: 1 },
    separator: { height: 10 },
    userRow: {
      minHeight: 74,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 11,
      borderRadius: 17,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    avatarWrap: { position: 'relative' },
    avatar: { width: 48, height: 48, borderRadius: 15 },
    avatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    avatarInitials: { color: colors.primary, fontSize: 15, fontWeight: '800' },
    onlineDot: {
      position: 'absolute',
      right: -1,
      bottom: -1,
      width: 13,
      height: 13,
      borderRadius: 7,
      backgroundColor: colors.confirm,
      borderWidth: 2,
      borderColor: colors.cardBackground,
    },
    userCopy: { flex: 1 },
    userName: { color: colors.textStrong, fontSize: 15, fontWeight: '700' },
    userRole: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
    checkbox: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.cardBackground,
    },
    checkboxSelected: { borderColor: colors.primary, backgroundColor: colors.primary },
    centerState: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    emptyText: { color: colors.textMuted, fontSize: 14, marginTop: 11 },
    errorText: {
      color: colors.error,
      fontSize: 12,
      marginHorizontal: 20,
      marginTop: 10,
      textAlign: 'center',
    },
    groupFooter: {
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 18,
      backgroundColor: colors.cardBackground,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    selectionText: {
      color: colors.textMuted,
      fontSize: 12,
      marginBottom: 8,
      textAlign: 'center',
    },
    createButton: {
      minHeight: 46,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: colors.primary,
    },
    createButtonDisabled: { backgroundColor: colors.disabled },
    createButtonText: { color: colors.white, fontSize: 15, fontWeight: '800' },
  });
}
