import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(
  colors: ColorPalette,
  topInset: number,
  bottomInset: number
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: Math.max(topInset, 24) + 14,
      paddingBottom: 14,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      backgroundColor: colors.background,
    },
    headerTitle: {
      flex: 1,
      color: colors.secondary,
      fontSize: 18,
      fontWeight: '700',
      marginHorizontal: 8,
      textAlign: 'center',
    },
    headerSpacer: { width: 40, height: 40 },
    listContent: {
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 30 + Math.max(bottomInset, 10),
    },
    emptyListContent: { flexGrow: 1 },
    description: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 21,
      marginBottom: 18,
    },
    inlineError: {
      color: colors.error,
      fontSize: 12,
      lineHeight: 18,
      marginTop: -8,
      marginBottom: 14,
    },
    separator: { height: 10 },
    userCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 18,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    avatar: { width: 50, height: 50, borderRadius: 16 },
    avatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    avatarText: { color: colors.primary, fontSize: 15, fontWeight: '800' },
    userCopy: { flex: 1, minWidth: 0 },
    userName: { color: colors.textStrong, fontSize: 15, fontWeight: '800' },
    userRole: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    blockedDate: { color: colors.gray, fontSize: 10, marginTop: 4 },
    unblockButton: {
      minWidth: 72,
      minHeight: 38,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: colors.primarySoft,
    },
    unblockText: { color: colors.primary, fontSize: 12, fontWeight: '800' },
    centerState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingBottom: Math.max(bottomInset, 10),
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
      paddingBottom: 70,
    },
    emptyIcon: {
      width: 74,
      height: 74,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 24,
      backgroundColor: colors.primarySoft,
    },
    stateTitle: {
      color: colors.textStrong,
      fontSize: 18,
      fontWeight: '800',
      marginTop: 16,
      textAlign: 'center',
    },
    stateDescription: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 20,
      marginTop: 7,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 16,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: colors.primary,
    },
    retryText: { color: colors.white, fontSize: 13, fontWeight: '800' },
  });
}
