import { StyleSheet } from 'react-native';
import { COLORS } from '../../../theme/colors';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 55,
    paddingBottom: 15,
    backgroundColor: COLORS.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.secondary },
  headerIconsContainer: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  headerIcon: { padding: 4, borderRadius: 8 },
  headerIconActive: { backgroundColor: '#E8F8F0' },
  scrollContent: { padding: 20, paddingBottom: 100 },
  profileCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarContainer: { position: 'relative', marginBottom: 14 },
  avatar: {
    width: 85,
    height: 85,
    borderRadius: 26,
    backgroundColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editAvatarButton: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: COLORS.primary,
    width: 26,
    height: 26,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.cardBackground,
  },
  profileName: { fontSize: 20, fontWeight: 'bold', color: COLORS.secondary },
  profileRuolo: { fontSize: 13, color: COLORS.primary, fontWeight: '600', marginTop: 4 },
  bioText: { fontSize: 13, color: '#5A5A6A', textAlign: 'center', marginTop: 10 },
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    backgroundColor: '#F8F9FA',
    paddingVertical: 10,
    borderRadius: 12,
    width: '100%',
  },
  statBox: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 15, fontWeight: 'bold', color: COLORS.secondary },
  statLabel: { fontSize: 11, color: COLORS.gray },
  statDivider: { width: 1, height: 20, backgroundColor: COLORS.border },
  registrationDataCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
    width: '100%',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 15, fontWeight: 'bold', color: COLORS.secondary },
  sectionSubtitle: { fontSize: 11, color: COLORS.gray, marginTop: 2, marginBottom: 12 },
  dataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F9FA',
  },
  eyeButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  eyeButtonActive: {
    backgroundColor: '#E8F8F0',
  },
  privacyButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  privacyButtonActive: {
    backgroundColor: '#E8F8F0',
    borderColor: '#2ECC71',
  },
  dataLabel: { fontSize: 11, color: COLORS.gray },
  dataValue: { fontSize: 13, fontWeight: '600', color: COLORS.secondary, marginTop: 1 },
  editUserForm: { width: '100%', gap: 6 },
  editLabel: { fontSize: 11, fontWeight: '700', color: COLORS.gray },
  editInput: {
    backgroundColor: '#F0F3FF',
    borderRadius: 8,
    padding: 8,
    fontSize: 14,
    color: COLORS.secondary,
  },
  buttonDelete: {
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#FFCCD1',
    backgroundColor: '#FFF5F5',
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDeleteText: {
    color: COLORS.delete,
    fontSize: 14,
    fontWeight: 'bold',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.border,
    padding: 4,
    borderRadius: 12,
    marginBottom: 16,
  },
  tabButton: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 9 },
  tabButtonActive: { backgroundColor: '#FFFFFF' },
  tabText: { fontSize: 13, fontWeight: '600', color: COLORS.primary },
  tabTextActive: { color: COLORS.secondary },
  tabContent: { gap: 12 },
  itemCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  itemIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemInfo: { flex: 1 },
  itemTitle: { fontSize: 14, fontWeight: 'bold', color: COLORS.secondary },
  itemSubtitle: { fontSize: 12, color: COLORS.primary },
  dateDurationText: { fontSize: 11, color: COLORS.gray, marginTop: 1 },
  btnModificaRecord: { backgroundColor: COLORS.primary, padding: 8, borderRadius: 8 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  actionSheetContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 35,
  },
  actionSheetTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.secondary,
    marginBottom: 8,
    textAlign: 'center',
  },
  actionSheetDescription: {
    fontSize: 13,
    color: COLORS.gray,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 18,
  },
  actionSheetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#F7F9FC',
    marginBottom: 12,
  },
  actionSheetBtnText: { fontSize: 15, color: COLORS.secondary, fontWeight: '600' },
  actionSheetCancelBtn: {
    borderBottomWidth: 0,
    marginTop: 8,
    backgroundColor: '#FFF5F5',
  },
  actionSheetCancelText: {
    color: COLORS.delete,
    fontWeight: 'bold',
  },
  navBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  navItem: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  navText: { fontSize: 11, color: '#8A8A9A', marginTop: 4 },
});

export const modalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 55,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: { fontSize: 17, fontWeight: 'bold', color: COLORS.secondary },
  scroll: { padding: 24, gap: 14 },
  label: { fontSize: 13, fontWeight: '600', color: COLORS.secondary, marginBottom: -4 },
  input: {
    backgroundColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: COLORS.secondary,
  },
  inputDatePicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
  },
  dateText: { fontSize: 15, color: COLORS.secondary, fontWeight: '500' },
  iosPickerWrapper: {
    backgroundColor: COLORS.secondary,
    borderRadius: 12,
    padding: 8,
    marginVertical: 4,
    height: 180,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 6,
  },
  checkboxLabel: { fontSize: 13, color: '#5A5A6A', fontWeight: '500' },
  buttonSubmit: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 15,
  },
  buttonSubmitText: { color: '#FFFFFF', fontSize: 15, fontWeight: 'bold' },
  buttonDelete: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#FFCCD1',
    backgroundColor: '#FFF5F5',
    marginTop: 10,
    marginBottom: 40,
  },
  buttonDeleteText: { color: COLORS.delete, fontSize: 15, fontWeight: 'bold' },
  scrollContent: { paddingBottom: 100 },
});
