import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(
  COLORS: ColorPalette,
  topInset: number,
  bottomInset: number
) {
  return StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: Math.max(topInset, 24) + 14,
    paddingBottom: 15,
    backgroundColor: COLORS.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: COLORS.secondary },
  headerIconsContainer: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  headerIcon: { padding: 4, borderRadius: 8 },
  headerIconActive: { backgroundColor: COLORS.successSoft },
  scrollContent: {
    padding: 20,
    paddingBottom: 88 + Math.max(bottomInset, 10),
  },
  profileCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 20,
  },
  coverContainer: {
    width: '100%',
    height: 164,
    backgroundColor: COLORS.primarySoft,
  },
  coverImage: { width: '100%', height: '100%' },
  coverFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
  },
  editCoverButton: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: COLORS.primary,
    borderWidth: 2,
    borderColor: COLORS.cardBackground,
  },
  profileContent: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  avatarContainer: { position: 'relative', marginTop: -43, marginBottom: 14 },
  avatar: {
    width: 85,
    height: 85,
    borderRadius: 26,
    backgroundColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: COLORS.cardBackground,
  },
  avatarImage: { width: '100%', height: '100%' },
  editAvatarButton: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: COLORS.primary,
    width: 26,
    height: 26,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.cardBackground,
  },
  profileName: { fontSize: 20, fontWeight: 'bold', color: COLORS.secondary },
  profileRuolo: { fontSize: 13, color: COLORS.primary, fontWeight: '600', marginTop: 4 },
  builderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: COLORS.primarySoft,
    marginTop: 10,
  },
  builderBadgeText: { fontSize: 12, color: COLORS.primary, fontWeight: '800' },
  bioText: { fontSize: 13, color: COLORS.textMuted, textAlign: 'center', marginTop: 10 },
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    backgroundColor: COLORS.surfaceMuted,
    paddingVertical: 10,
    borderRadius: 12,
    width: '100%',
  },
  statBox: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 15, fontWeight: 'bold', color: COLORS.secondary },
  statLabel: { fontSize: 11, color: COLORS.gray },
  statDivider: { width: 1, height: 20, backgroundColor: COLORS.border },
  registrationDataCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
    width: '100%',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 15, fontWeight: 'bold', color: COLORS.secondary },
  sectionSubtitle: { fontSize: 11, color: COLORS.gray, marginTop: 2, marginBottom: 12 },
  dataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.surfaceMuted,
  },
  eyeButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  eyeButtonActive: {
    backgroundColor: COLORS.successSoft,
  },
  privacyButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  privacyButtonActive: {
    backgroundColor: COLORS.successSoft,
    borderColor: COLORS.confirm,
  },
  dataLabel: { fontSize: 11, color: COLORS.gray },
  dataValue: { fontSize: 13, fontWeight: '600', color: COLORS.secondary, marginTop: 1 },
  editUserForm: { width: '100%', gap: 6 },
  editLabel: { fontSize: 11, fontWeight: '700', color: COLORS.gray },
  editInput: {
    backgroundColor: COLORS.inputSurface,
    borderRadius: 8,
    padding: 8,
    fontSize: 14,
    color: COLORS.secondary,
  },
  buttonDelete: {
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.dangerBorder,
    backgroundColor: COLORS.dangerSoft,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonDeleteText: {
    color: COLORS.delete,
    fontSize: 14,
    fontWeight: 'bold',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.border,
    padding: 4,
    borderRadius: 12,
    marginBottom: 16,
  },
  tabButton: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 9 },
  tabButtonActive: { backgroundColor: COLORS.cardBackground },
  tabText: { fontSize: 13, fontWeight: '600', color: COLORS.primary },
  tabTextActive: { color: COLORS.textStrong },
  tabPagerContent: { alignItems: 'flex-start' },
  tabContent: { gap: 12 },
  itemDescriptionPreview: {
    color: COLORS.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 5,
  },
  itemCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  itemIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  itemImage: { width: '100%', height: '100%' },
  itemInfo: { flex: 1 },
  itemTitle: { fontSize: 14, fontWeight: 'bold', color: COLORS.secondary },
  itemSubtitle: { fontSize: 12, color: COLORS.primary },
  dateDurationText: { fontSize: 11, color: COLORS.gray, marginTop: 1 },
  btnModificaRecord: { backgroundColor: COLORS.primary, padding: 8, borderRadius: 8 },
  postsSection: { gap: 12, marginTop: 22 },
  postsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  postsTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.secondary },
  postsSubtitle: { fontSize: 12, color: COLORS.gray, marginTop: 3 },
  addPostButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
  },
  addPostButtonText: { color: COLORS.white, fontSize: 13, fontWeight: '800' },
  emptyPostsCard: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: 22,
    borderRadius: 16,
    backgroundColor: COLORS.cardBackground,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  emptyPostsTitle: { color: COLORS.secondary, fontSize: 15, fontWeight: '800' },
  emptyPostsText: { color: COLORS.textMuted, fontSize: 13, textAlign: 'center' },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'flex-end',
  },
  actionSheetContainer: {
    backgroundColor: COLORS.cardBackground,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 35,
  },
  actionSheetTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.secondary,
    marginBottom: 8,
    textAlign: 'center',
  },
  actionSheetDescription: {
    fontSize: 13,
    color: COLORS.gray,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 18,
  },
  actionSheetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: COLORS.actionSurface,
    marginBottom: 12,
  },
  actionSheetBtnText: { fontSize: 15, color: COLORS.secondary, fontWeight: '600' },
  actionSheetCancelBtn: {
    borderBottomWidth: 0,
    marginTop: 8,
    backgroundColor: COLORS.dangerSoft,
  },
  actionSheetCancelText: {
    color: COLORS.delete,
    fontWeight: 'bold',
  },
  navBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: COLORS.cardBackground,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  navItem: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  navText: { fontSize: 11, color: COLORS.gray, marginTop: 4 },
});
}

export const createModalStyles = (
  COLORS: ColorPalette,
  topInset: number,
  bottomInset: number
) => StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Math.max(topInset, 24) + 14,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: { fontSize: 17, fontWeight: 'bold', color: COLORS.textStrong },
  scroll: { padding: 24, gap: 14, paddingBottom: 40 + Math.max(bottomInset, 10) },
  label: { fontSize: 13, fontWeight: '600', color: COLORS.textStrong, marginBottom: -4 },
  input: {
    backgroundColor: COLORS.inputSurface,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: COLORS.textStrong,
  },
  inputDatePicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: COLORS.inputSurface,
    borderRadius: 12,
    padding: 14,
  },
  projectImagePicker: {
    minHeight: 132,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    overflow: 'hidden',
  },
  projectImage: { width: '100%', height: 132 },
  projectImageText: { color: COLORS.primary, fontSize: 13, fontWeight: '700' },
  postInput: {
    minHeight: 150,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    lineHeight: 21,
    color: COLORS.textStrong,
    backgroundColor: COLORS.inputSurface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  postImageWrap: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: COLORS.border,
  },
  postImage: { width: '100%', height: 190 },
  removePostImageButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 30,
    height: 30,
    borderRadius: 9,
    backgroundColor: COLORS.overlay,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.actionSurface,
  },
  addImageText: { color: COLORS.primary, fontSize: 13, fontWeight: '700' },
  dateText: { fontSize: 15, color: COLORS.textStrong, fontWeight: '500' },
  iosPickerWrapper: {
    backgroundColor: COLORS.secondary,
    borderRadius: 12,
    padding: 8,
    marginVertical: 4,
    height: 180,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 6,
  },
  checkboxLabel: { fontSize: 13, color: COLORS.textMuted, fontWeight: '500' },
  buttonSubmit: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 15,
  },
  buttonSubmitText: { color: COLORS.white, fontSize: 15, fontWeight: 'bold' },
  buttonDelete: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: COLORS.dangerBorder,
    backgroundColor: COLORS.dangerSoft,
    marginTop: 10,
    marginBottom: 40,
  },
  buttonDeleteText: { color: COLORS.delete, fontSize: 15, fontWeight: 'bold' },
});
