import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(
  colors: ColorPalette,
  topInset: number,
  bottomInset: number
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: Math.max(topInset, 24) + 14,
      paddingBottom: 14,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    headerTitle: {
      flex: 1,
      marginHorizontal: 8,
      textAlign: 'center',
      color: colors.secondary,
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: { width: 40, height: 40 },
    scrollContent: {
      padding: 20,
      paddingBottom: 40 + Math.max(bottomInset, 10),
    },
    card: {
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
    },
    label: {
      color: colors.textStrong,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 7,
      marginTop: 13,
    },
    input: {
      minHeight: 52,
      borderRadius: 13,
      paddingHorizontal: 14,
      backgroundColor: colors.inputSurface,
      color: colors.textStrong,
      borderWidth: 1,
      borderColor: colors.border,
    },
    readonlyField: {
      minHeight: 52,
      justifyContent: 'center',
      borderRadius: 13,
      paddingHorizontal: 14,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    readonlyText: { color: colors.textMuted, fontSize: 14 },
    passwordField: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 13,
      paddingHorizontal: 14,
      backgroundColor: colors.inputSurface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    passwordInput: { flex: 1, color: colors.textStrong, paddingVertical: 12 },
    submitButton: {
      minHeight: 52,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 24,
      borderRadius: 14,
      backgroundColor: colors.primary,
    },
    submitButtonDisabled: { opacity: 0.65 },
    submitButtonText: { color: colors.white, fontSize: 15, fontWeight: '800' },
    biometricIcon: {
      width: 66,
      height: 66,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 22,
      backgroundColor: colors.primarySoft,
      marginTop: 4,
    },
    biometricTitle: {
      color: colors.textStrong,
      fontSize: 19,
      fontWeight: '800',
      textAlign: 'center',
      marginTop: 16,
    },
    biometricDescription: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 20,
      textAlign: 'center',
      marginTop: 8,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      marginTop: 24,
      paddingTop: 18,
      borderTopWidth: 1,
      borderTopColor: colors.divider,
    },
    statusCopy: { flex: 1 },
    statusLabel: { color: colors.gray, fontSize: 12 },
    statusValue: {
      color: colors.textStrong,
      fontSize: 14,
      fontWeight: '700',
      marginTop: 4,
    },
    enabledText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'right',
      marginTop: 10,
    },
  });
}
