import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 55,
      paddingBottom: 14,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    headerTitle: { color: colors.secondary, fontSize: 19, fontWeight: '700' },
    headerSpacer: { width: 40, height: 40 },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 28,
      paddingBottom: 48,
    },
    intro: { marginBottom: 20 },
    introTitle: { color: colors.textStrong, fontSize: 24, fontWeight: '800' },
    introDescription: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 21,
      marginTop: 6,
    },
    menuCard: {
      overflow: 'hidden',
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    menuRow: {
      minHeight: 78,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    menuRowLast: { borderBottomWidth: 0 },
    iconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    menuCopy: { flex: 1 },
    menuTitle: { color: colors.textStrong, fontSize: 15, fontWeight: '700' },
    menuDescription: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 3,
    },
    footer: { alignItems: 'center', marginTop: 'auto', paddingTop: 44 },
    versionText: { color: colors.gray, fontSize: 12 },
    copyrightText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 7,
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      minWidth: 120,
      marginTop: 22,
      paddingHorizontal: 18,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: colors.dangerSoft,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
    },
    logoutText: { color: colors.delete, fontSize: 14, fontWeight: '700' },
  });
}
