import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 55,
      paddingBottom: 14,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    headerTitle: {
      flex: 1,
      marginHorizontal: 8,
      textAlign: 'center',
      color: colors.secondary,
      fontSize: 18,
      fontWeight: '700',
    },
    headerSpacer: { width: 40, height: 40 },
    scrollContent: { padding: 20, paddingBottom: 48 },
    card: {
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
      marginBottom: 16,
    },
    iconBox: {
      width: 62,
      height: 62,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 20,
      backgroundColor: colors.primarySoft,
      marginBottom: 16,
    },
    title: {
      color: colors.textStrong,
      fontSize: 19,
      fontWeight: '800',
      textAlign: 'center',
    },
    description: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 21,
      textAlign: 'center',
      marginTop: 8,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingVertical: 13,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    infoRowLast: { borderBottomWidth: 0 },
    infoLabel: { color: colors.gray, fontSize: 13 },
    infoValue: {
      flex: 1,
      color: colors.textStrong,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'right',
    },
    primaryButton: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 14,
      backgroundColor: colors.primary,
      paddingHorizontal: 18,
    },
    primaryButtonDisabled: { opacity: 0.55 },
    primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: '800' },
    dangerButton: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 14,
      backgroundColor: colors.dangerSoft,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
      paddingHorizontal: 18,
    },
    dangerButtonDisabled: { opacity: 0.45 },
    dangerButtonText: { color: colors.delete, fontSize: 15, fontWeight: '800' },
    warningText: {
      color: colors.delete,
      fontSize: 13,
      lineHeight: 20,
      textAlign: 'center',
      marginTop: 12,
    },
    label: {
      color: colors.textStrong,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 7,
      marginTop: 13,
    },
    input: {
      minHeight: 52,
      borderRadius: 13,
      paddingHorizontal: 14,
      backgroundColor: colors.inputSurface,
      color: colors.textStrong,
      borderWidth: 1,
      borderColor: colors.border,
    },
    multilineInput: {
      minHeight: 150,
      paddingTop: 14,
      textAlignVertical: 'top',
    },
    counter: { color: colors.gray, fontSize: 11, textAlign: 'right', marginTop: 5 },
    subjectGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    subjectButton: {
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    subjectButtonActive: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    subjectText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
    subjectTextActive: { color: colors.primary },
    confirmationInput: {
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 1,
      marginVertical: 18,
    },
  });
}
