import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(
  colors: ColorPalette,
  topInset: number,
  bottomInset: number
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: Math.max(topInset, 24) + 14,
      paddingBottom: 14,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    headerTitle: {
      flex: 1,
      color: colors.secondary,
      fontSize: 18,
      fontWeight: '700',
      textAlign: 'center',
      marginHorizontal: 8,
    },
    headerSpacer: { width: 40, height: 40 },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 28,
      paddingBottom: 40 + Math.max(bottomInset, 10),
    },
    description: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 21,
      marginBottom: 20,
    },
    menuCard: {
      overflow: 'hidden',
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    menuRow: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 13,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    menuRowLast: { borderBottomWidth: 0 },
    iconBox: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    menuCopy: { flex: 1 },
    menuTitle: { color: colors.textStrong, fontSize: 15, fontWeight: '700' },
    menuValue: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
    badge: {
      color: colors.primary,
      fontSize: 10,
      fontWeight: '700',
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: colors.primarySoft,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      padding: 24,
      backgroundColor: colors.overlay,
    },
    modalCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalTitle: {
      color: colors.textStrong,
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 12,
    },
    optionRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    optionText: { color: colors.textMuted, fontSize: 15, fontWeight: '600' },
    optionTextSelected: { color: colors.primary },
  });
}
