import type { AppLanguage } from '../../../theme/AppPreferencesProvider';

export const SETTINGS_COPY = {
  it: {
    settings: 'Impostazioni',
    introTitle: 'Le tue impostazioni',
    introDescription: 'Personalizza Crevia e gestisci il tuo account.',
    version: 'Versione',
    exit: 'Esci',
    logoutTitle: 'Uscire da Crevia?',
    logoutMessage: 'Dovrai effettuare nuovamente l’accesso per usare l’app.',
    cancel: 'Annulla',
    backToProfile: 'Torna al profilo',
    backToSettings: 'Torna alle impostazioni',
    categories: {
      personalization: {
        title: 'Personalizzazione App',
        summary: 'Lingua, tema e feedback aptico',
        description: 'Scegli come Crevia appare e risponde alle tue azioni.',
        items: ['Lingua', 'Tema', 'Feedback aptico'],
      },
      profilePrivacy: {
        title: 'Profilo e Privacy',
        summary: 'Credenziali, privacy e accesso',
        description: 'Gestisci le credenziali e la sicurezza del tuo profilo.',
        items: [
          'Modifica email',
          'Modifica password',
          'Passkey',
          'Utenti bloccati',
          'Termini e condizioni',
        ],
      },
      appExperience: {
        title: 'Esperienza in App',
        summary: 'Sincronizzazione dei contatti',
        description: 'Connetti Crevia alle funzionalità del tuo dispositivo.',
        items: ['Sincronizza contatti'],
      },
      accountManagement: {
        title: 'Gestione Account',
        summary: 'Sospensione ed eliminazione account',
        description: 'Controlla lo stato e la permanenza del tuo account.',
        items: ['Sospendi account', 'Elimina account'],
      },
      help: {
        title: 'Aiuto',
        summary: 'Assistenza e richieste di supporto',
        description: 'Ricevi assistenza dal team Crevia.',
        items: ['Contattaci'],
      },
    },
    subscriberOnly: 'Solo abbonati',
    active: 'Attivo',
    inactive: 'Non attivo',
    chooseLanguage: 'Seleziona la lingua',
    chooseTheme: 'Seleziona il tema',
    languages: { it: 'Italiano', en: 'English' },
    themes: { automatic: 'Automatico', light: 'Chiaro', dark: 'Scuro' },
  },
  en: {
    settings: 'Settings',
    introTitle: 'Your settings',
    introDescription: 'Personalize Crevia and manage your account.',
    version: 'Version',
    exit: 'Log out',
    logoutTitle: 'Log out of Crevia?',
    logoutMessage: 'You will need to sign in again to use the app.',
    cancel: 'Cancel',
    backToProfile: 'Back to profile',
    backToSettings: 'Back to settings',
    categories: {
      personalization: {
        title: 'App Personalization',
        summary: 'Language, theme and haptic feedback',
        description: 'Choose how Crevia looks and responds to your actions.',
        items: ['Language', 'Theme', 'Haptic feedback'],
      },
      profilePrivacy: {
        title: 'Profile and Privacy',
        summary: 'Credentials, privacy and access',
        description: 'Manage your profile credentials and security.',
        items: [
          'Change email',
          'Change password',
          'Passkey',
          'Blocked users',
          'Terms and conditions',
        ],
      },
      appExperience: {
        title: 'App Experience',
        summary: 'Contact synchronization',
        description: 'Connect Crevia to your device features.',
        items: ['Sync contacts'],
      },
      accountManagement: {
        title: 'Account Management',
        summary: 'Account suspension and deletion',
        description: 'Control your account status and permanence.',
        items: ['Suspend account', 'Delete account'],
      },
      help: {
        title: 'Help',
        summary: 'Support and assistance requests',
        description: 'Get help from the Crevia team.',
        items: ['Contact us'],
      },
    },
    subscriberOnly: 'Subscribers only',
    active: 'Enabled',
    inactive: 'Disabled',
    chooseLanguage: 'Select language',
    chooseTheme: 'Select theme',
    languages: { it: 'Italiano', en: 'English' },
    themes: { automatic: 'Automatic', light: 'Light', dark: 'Dark' },
  },
} as const satisfies Record<AppLanguage, object>;
