import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(
  colors: ColorPalette,
  topInset: number,
  bottomInset: number
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      paddingHorizontal: 20,
      paddingTop: Math.max(topInset, 24) + 14,
      paddingBottom: 18,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    headerCopy: { flex: 1 },
    addButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 15,
      backgroundColor: colors.primary,
    },
    eyebrow: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    title: {
      color: colors.textStrong,
      fontSize: 28,
      fontWeight: '800',
      marginTop: 3,
    },
    searchBar: {
      height: 46,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      marginHorizontal: 20,
      marginTop: 16,
      paddingHorizontal: 14,
      borderRadius: 15,
      backgroundColor: colors.inputSurface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: { flex: 1, color: colors.textStrong, fontSize: 15 },
    listContent: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 88 + Math.max(bottomInset, 10),
    },
    separator: { height: 11 },
    conversationCard: {
      minHeight: 82,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      paddingHorizontal: 14,
      paddingVertical: 13,
      borderRadius: 18,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    avatarWrap: { position: 'relative' },
    avatar: { width: 54, height: 54, borderRadius: 18 },
    avatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    avatarInitials: { color: colors.primary, fontSize: 17, fontWeight: '800' },
    onlineDot: {
      position: 'absolute',
      right: -1,
      bottom: -1,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: colors.confirm,
      borderWidth: 2,
      borderColor: colors.cardBackground,
    },
    conversationBody: { flex: 1, minWidth: 0 },
    rowTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    participantName: {
      flex: 1,
      color: colors.textStrong,
      fontSize: 16,
      fontWeight: '700',
    },
    time: { color: colors.gray, fontSize: 11 },
    moreButton: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: -4,
    },
    rowBottom: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 5 },
    messagePreview: { flex: 1, color: colors.textMuted, fontSize: 13, lineHeight: 18 },
    messageUnread: { color: colors.textStrong, fontWeight: '600' },
    unreadBadge: {
      minWidth: 22,
      height: 22,
      paddingHorizontal: 6,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 11,
      backgroundColor: colors.primary,
    },
    unreadText: { color: colors.white, fontSize: 11, fontWeight: '800' },
    centerState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingBottom: 85,
    },
    emptyIcon: {
      width: 76,
      height: 76,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 25,
      backgroundColor: colors.primarySoft,
    },
    stateTitle: {
      color: colors.textStrong,
      fontSize: 19,
      fontWeight: '800',
      marginTop: 18,
      textAlign: 'center',
    },
    stateDescription: {
      color: colors.textMuted,
      fontSize: 14,
      lineHeight: 21,
      marginTop: 7,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 18,
      paddingHorizontal: 20,
      paddingVertical: 11,
      borderRadius: 13,
      backgroundColor: colors.primary,
    },
    retryText: { color: colors.white, fontSize: 14, fontWeight: '700' },
  });
}
