import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 50,
      paddingBottom: 13,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      backgroundColor: colors.background,
    },
    headerTitle: { color: colors.textStrong, fontSize: 18, fontWeight: '800' },
    headerSpacer: { width: 40, height: 40 },
    content: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 44 },
    hero: { alignItems: 'center' },
    contactAvatar: { width: 104, height: 104, borderRadius: 32 },
    contactAvatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    contactInitials: { color: colors.primary, fontSize: 30, fontWeight: '800' },
    contactName: { color: colors.textStrong, fontSize: 23, fontWeight: '800', marginTop: 15 },
    contactRole: { color: colors.textMuted, fontSize: 13, marginTop: 5 },
    presenceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 8 },
    presenceDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.confirm },
    presenceDotOffline: { backgroundColor: colors.gray },
    presenceText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
    blockedNotice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      marginTop: 24,
      padding: 13,
      borderRadius: 14,
      backgroundColor: colors.dangerSoft,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
    },
    blockedNoticeText: { flex: 1, color: colors.textMuted, fontSize: 12, lineHeight: 18 },
    inlineError: { color: colors.error, fontSize: 12, marginTop: 12, textAlign: 'center' },
    actionsCard: {
      overflow: 'hidden',
      marginTop: 24,
      borderRadius: 18,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    actionRow: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    actionRowLast: { borderBottomWidth: 0 },
    actionIcon: {
      width: 38,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      backgroundColor: colors.dangerSoft,
    },
    actionIconPrimary: { backgroundColor: colors.primarySoft },
    actionText: { flex: 1, color: colors.textStrong, fontSize: 14, fontWeight: '700' },
    actionTextDanger: { color: colors.error },
    actionTextDisabled: { color: colors.gray },
    centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    errorText: { color: colors.error, fontSize: 14, textAlign: 'center' },
  });
}
