import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    keyboardView: { flex: 1 },
    header: {
      minHeight: 96,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 44,
      paddingBottom: 12,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      backgroundColor: colors.background,
    },
    groupHeaderButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    avatarWrap: { position: 'relative' },
    avatar: { width: 42, height: 42, borderRadius: 14 },
    avatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    avatarInitials: { color: colors.primary, fontSize: 14, fontWeight: '800' },
    onlineDot: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.confirm,
      borderWidth: 2,
      borderColor: colors.cardBackground,
    },
    headerCopy: { flex: 1 },
    participantName: { color: colors.textStrong, fontSize: 16, fontWeight: '800' },
    presence: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    typingText: { color: colors.primary, fontWeight: '600' },
    messagesContent: { flexGrow: 1, paddingHorizontal: 16, paddingVertical: 18 },
    messageGroup: { maxWidth: '86%', marginBottom: 12 },
    messageGroupOwn: { alignSelf: 'flex-end', alignItems: 'flex-end' },
    messageGroupOther: { alignSelf: 'flex-start', alignItems: 'flex-start' },
    messageBubble: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 7, borderRadius: 18 },
    messageBubbleOwn: { backgroundColor: colors.primary, borderBottomRightRadius: 5 },
    messageBubbleOther: {
      backgroundColor: colors.cardBackground,
      borderBottomLeftRadius: 5,
      borderWidth: 1,
      borderColor: colors.border,
    },
    messageBubbleFailed: { borderWidth: 1, borderColor: colors.error },
    quotedReply: {
      minWidth: 150,
      marginBottom: 8,
      paddingLeft: 9,
      paddingVertical: 5,
      paddingRight: 8,
      borderLeftWidth: 3,
      borderRadius: 6,
    },
    quotedReplyOwn: { borderLeftColor: colors.white, backgroundColor: colors.toggleTrackOn },
    quotedReplyOther: { borderLeftColor: colors.primary, backgroundColor: colors.primarySoft },
    quotedReplyAuthor: { color: colors.primary, fontSize: 11, fontWeight: '800' },
    quotedReplyText: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
    quotedReplyTextOwn: { color: colors.white },
    messageImage: { width: 220, height: 160, borderRadius: 12, marginBottom: 3 },
    messageText: { fontSize: 15, lineHeight: 21 },
    messageTextWithAttachment: { marginTop: 7 },
    messageTextOwn: { color: colors.white },
    messageTextOther: { color: colors.textStrong },
    messageMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 3,
      marginTop: 3,
    },
    messageTime: { fontSize: 10 },
    messageTimeOwn: { color: colors.white, opacity: 0.8 },
    messageTimeOther: { color: colors.gray },
    reactionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 4 },
    reactionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 12,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    reactionEmoji: { fontSize: 13 },
    reactionCount: { color: colors.textMuted, fontSize: 10, fontWeight: '700' },
    messageActions: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 6,
      paddingHorizontal: 6,
      paddingVertical: 5,
      borderRadius: 16,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    quickReaction: { width: 36, height: 34, alignItems: 'center', justifyContent: 'center' },
    quickReactionText: { fontSize: 19 },
    actionDivider: { width: 1, height: 22, backgroundColor: colors.border },
    typingBubble: {
      width: 58,
      height: 34,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderRadius: 17,
      borderBottomLeftRadius: 5,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    typingDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.gray },
    composerContainer: {
      backgroundColor: colors.cardBackground,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    composerReply: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginHorizontal: 14,
      marginTop: 9,
      paddingLeft: 11,
      paddingRight: 8,
      paddingVertical: 7,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
      borderRadius: 9,
      backgroundColor: colors.primarySoft,
    },
    composerReplyCopy: { flex: 1 },
    composerReplyLabel: { color: colors.primary, fontSize: 11, fontWeight: '800' },
    composerReplyText: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    pendingAttachments: {
      flexDirection: 'row',
      gap: 9,
      paddingHorizontal: 14,
      paddingTop: 9,
    },
    pendingAttachment: { position: 'relative' },
    pendingImage: { width: 58, height: 58, borderRadius: 12 },
    pendingAudio: {
      height: 48,
      minWidth: 92,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: colors.primarySoft,
    },
    pendingAudioText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
    removeAttachment: {
      position: 'absolute',
      top: -5,
      right: -5,
      width: 20,
      height: 20,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      backgroundColor: colors.textStrong,
    },
    composer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 16,
    },
    composerIconButton: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: colors.primarySoft,
    },
    input: {
      flex: 1,
      minHeight: 42,
      maxHeight: 112,
      paddingHorizontal: 15,
      paddingTop: 10,
      paddingBottom: 10,
      borderRadius: 18,
      color: colors.textStrong,
      fontSize: 15,
      backgroundColor: colors.inputSurface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    recordingState: {
      flex: 1,
      height: 42,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 14,
      borderRadius: 18,
      backgroundColor: colors.dangerSoft,
    },
    recordingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.error },
    recordingTime: { color: colors.textStrong, fontSize: 13, fontWeight: '700' },
    cancelRecording: { color: colors.error, fontSize: 12, fontWeight: '700' },
    sendButton: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: colors.primary,
    },
    recordingButton: { backgroundColor: colors.error },
    sendButtonDisabled: { backgroundColor: colors.disabled },
    centerState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
    },
    errorTitle: {
      color: colors.textStrong,
      fontSize: 18,
      fontWeight: '800',
      marginTop: 14,
      textAlign: 'center',
    },
    retryButton: {
      marginTop: 17,
      paddingHorizontal: 20,
      paddingVertical: 11,
      borderRadius: 13,
      backgroundColor: colors.primary,
    },
    retryText: { color: colors.white, fontSize: 14, fontWeight: '700' },
    sendError: {
      color: colors.error,
      fontSize: 12,
      paddingHorizontal: 16,
      paddingVertical: 7,
      textAlign: 'center',
      backgroundColor: colors.dangerSoft,
    },
    readOnlyComposer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      minHeight: 70,
      paddingHorizontal: 20,
      paddingBottom: 10,
      backgroundColor: colors.cardBackground,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    readOnlyComposerText: {
      flex: 1,
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'center',
    },
  });
}
