import { StyleSheet } from 'react-native';

import type { ColorPalette } from '../../../theme/colors';

export default function createStyles(colors: ColorPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 50,
      paddingBottom: 13,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      backgroundColor: colors.background,
    },
    headerTitle: { color: colors.textStrong, fontSize: 18, fontWeight: '800' },
    headerSpacer: { width: 40, height: 40 },
    content: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 44 },
    hero: { alignItems: 'center' },
    groupAvatarWrap: { position: 'relative' },
    groupAvatar: { width: 104, height: 104, borderRadius: 32 },
    groupAvatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    editAvatarBadge: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      backgroundColor: colors.primary,
      borderWidth: 3,
      borderColor: colors.background,
    },
    groupTitle: {
      color: colors.textStrong,
      fontSize: 23,
      fontWeight: '800',
      marginTop: 15,
      textAlign: 'center',
    },
    groupSubtitle: { color: colors.textMuted, fontSize: 13, marginTop: 5 },
    changePhotoLabel: { color: colors.primary, fontSize: 12, fontWeight: '700', marginTop: 7 },
    leftNotice: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginTop: 24,
      padding: 14,
      borderRadius: 15,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.border,
    },
    leftNoticeCopy: { flex: 1 },
    leftNoticeTitle: { color: colors.textStrong, fontSize: 13, fontWeight: '700' },
    leftNoticeText: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 3 },
    inlineError: { color: colors.error, fontSize: 12, marginTop: 14, textAlign: 'center' },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 28,
      marginBottom: 10,
    },
    sectionTitle: { color: colors.textStrong, fontSize: 16, fontWeight: '800' },
    sectionCount: { color: colors.gray, fontSize: 13, fontWeight: '700' },
    addParticipantsButton: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      marginBottom: 10,
      paddingHorizontal: 13,
      borderRadius: 16,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    addParticipantsIcon: {
      width: 38,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      backgroundColor: colors.primarySoft,
    },
    addParticipantsText: {
      flex: 1,
      color: colors.primary,
      fontSize: 14,
      fontWeight: '800',
    },
    participantCard: {
      overflow: 'hidden',
      borderRadius: 18,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    participantRow: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      paddingHorizontal: 13,
      paddingVertical: 11,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    participantRowLast: { borderBottomWidth: 0 },
    avatar: { width: 46, height: 46, borderRadius: 14 },
    avatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    avatarInitials: { color: colors.primary, fontSize: 14, fontWeight: '800' },
    participantCopy: { flex: 1 },
    participantNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    participantName: { flexShrink: 1, color: colors.textStrong, fontSize: 14, fontWeight: '700' },
    participantRole: { color: colors.textMuted, fontSize: 11, marginTop: 3 },
    mainBadge: {
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: colors.primarySoft,
    },
    mainBadgeText: { color: colors.primary, fontSize: 9, fontWeight: '800' },
    memberMenuButton: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 11,
      backgroundColor: colors.primarySoft,
    },
    leaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      minHeight: 48,
      marginTop: 24,
      borderRadius: 15,
      backgroundColor: colors.dangerSoft,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
    },
    leaveButtonText: { color: colors.error, fontSize: 14, fontWeight: '800' },
    centerState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    errorText: { color: colors.error, fontSize: 14, textAlign: 'center' },
  });
}
